apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    qcloud-app: polaris-dns-consumer
  name: polaris-dns-consumer
  namespace: default
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: polaris-dns-consumer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: polaris-dns-consumer
    spec:
      containers:
        - name: polaris-dns-consumer
          image: polarismesh/polaris-dns-consumer:latest
          command: ["./consumer"]
          args:
            [
              "--port=20000",
              "--calleeNamespace=default",
              "--calleeService=echoserver",
              "--calleePort=10000",
            ]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
